### ISSUE TITLE
Cell phone can not be added to the game when default image is used.

### ISSUE THREAD

**Issue by LMH01** [LMH01/MGT2_Mod_Tool#104]
**Describe the bug**
Tool throws exception when it is tried to add a cell phone while using the default image.

This is the stacktrace:
```
Copying images for content Android 7 NougatError in thread: runnableAddplatformThe process has been terminated!Stacktrace:com.github.lmh01.mgt2mt.content.managed.ModProcessingException: Unable to add contents of type platform	at com.github.lmh01.mgt2mt.content.managed.AbstractBaseContentManager.addContents(AbstractBaseContentManager.java:186)	at com.github.lmh01.mgt2mt.content.managed.AbstractBaseContentManager.addContent(AbstractBaseContentManager.java:148)	at com.github.lmh01.mgt2mt.content.manager.PlatformManager.openAddModGui(PlatformManager.java:567)	at com.github.lmh01.mgt2mt.content.managed.AbstractBaseContentManager.lambda$addModMenuItemAction$3(AbstractBaseContentManager.java:68)	at com.github.lmh01.mgt2mt.util.handler.ThreadHandler.lambda$startModThread$3(ThreadHandler.java:131)	at java.lang.Thread.run(Unknown Source)	at java.lang.Thread.run(Unknown Source)Caused by: com.github.lmh01.mgt2mt.content.managed.ModProcessingException: Unable to add image files for Android 7 Nougat	at com.github.lmh01.mgt2mt.content.managed.AbstractBaseContentManager.addContents(AbstractBaseContentManager.java:176)	... 6 moreCaused by: java.nio.file.NoSuchFileException: C:\Program Files (x86)\Steam\steamapps\common\Mad Games Tycoon 2\Mad Games Tycoon 2_Data\Extern\Icons_Platforms\iPhone4.png	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)	at sun.nio.fs.WindowsFileCopy.copy(Unknown Source)	at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)	at java.nio.file.Files.copy(Unknown Source)	at com.github.lmh01.mgt2mt.content.instances.Platform.addPictures(Platform.java:184)	at com.github.lmh01.mgt2mt.content.managed.AbstractBaseContentManager.addContents(AbstractBaseContentManager.java:174)	... 6 more
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v4.4.0

**Additional information**
Bug was submitted by `Perfect Gaming Future` via steam.

**Comment by LMH01** [comment]
Bug is not reproducible, `iPhone4.png` exists in the game files.
Bug submitter must have a faulty game installation.
