### ISSUE TITLE
Unable to analyze game file for mod anti cheat

### ISSUE THREAD

**Issue by mester90** [LMH01/MGT2_Mod_Tool#105]
hi i have this problem i cant modify anything 

this is the error mgt2 show me

com.github.lmh01.mgt2mt.content.managed.ModProcessingException: Unable to analyze game file for mod anti cheat
	at com.github.lmh01.mgt2mt.content.managed.AbstractAdvancedContentManager.analyzeFile(AbstractAdvancedContentManager.java:263)
	at com.github.lmh01.mgt2mt.content.managed.ContentAdministrator.analyzeContents(ContentAdministrator.java:47)
	at com.github.lmh01.mgt2mt.windows.WindowMain.checkActionAvailability(WindowMain.java:242)
	at com.github.lmh01.mgt2mt.windows.WindowSettings.lambda$new$10(WindowSettings.java:292)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: Mad Games Tycoon 2_Data\Extern\Text\DATA\AntiCheat.txt (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.github.lmh01.mgt2mt.data_stream.DataStreamHelper.parseDataFile(DataStreamHelper.java:76)
	at com.github.lmh01.mgt2mt.content.managed.AbstractAdvancedContentManager.analyzeFile(AbstractAdvancedContentManager.java:243)
	... 40 more

com.github.lmh01.mgt2mt.content.managed.ModProcessingException: Unable to analyze game file for mod anti cheat
	at com.github.lmh01.mgt2mt.content.managed.AbstractAdvancedContentManager.analyzeFile(AbstractAdvancedContentManager.java:263)
	at com.github.lmh01.mgt2mt.content.managed.ContentAdministrator.analyzeContents(ContentAdministrator.java:47)
	at com.github.lmh01.mgt2mt.windows.WindowMain.checkActionAvailability(WindowMain.java:242)
	at com.github.lmh01.mgt2mt.windows.WindowSettings.lambda$new$8(WindowSettings.java:255)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: Mad Games Tycoon 2_Data\Extern\Text\DATA\AntiCheat.txt (The system cannot find the path specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at com.github.lmh01.mgt2mt.data_stream.DataStreamHelper.parseDataFile(DataStreamHelper.java:76)
	at com.github.lmh01.mgt2mt.content.managed.AbstractAdvancedContentManager.analyzeFile(AbstractAdvancedContentManager.java:243)
	... 40 more
	
	
any solution please and thank uu

**Comment by LMH01** [comment]
It seems like the file is missing: `Caused by: java.io.FileNotFoundException: Mad Games Tycoon 2_Data\Extern\Text\DATA\AntiCheat.txt (The system cannot find the path specified)`
Is also seems like the path to the MGT2 folder was not set correctly.

You can try to fix this problem by doing the following:
1. verifying the integrity of the game files (using steam)
2. if that did not work you can open the mod tool and go to: `File -> Uninstall`. Select everything and click ok. Then restart the mod tool and select the correct game path.

You did not disable any safety features right?

**Comment by mester90** [comment]
no i didnt disable anything of safety features 
the last version of the trainer work with the game for me is MGT2_Mod_Tool_3.2.0 this work perfect no errors at all 
all the highers versions same error from  v4.0.0 to v4.4.0

**Comment by LMH01** [comment]
Can you try to delete everything in this folder and restart the mod tool?: `%appdata%/LMH01`

It could also help if you could sent me the latest log file beforehand. The log file is located at `%appdata%/LMH01/MGT2_Mod_Manager` and called `latest.log`.

**Comment by mester90** [comment]
I CANT FIND THE LOG file of the version 4.4.0 
this pic you can see the difference between 3.2.0 and 4.4.0 
in v3.2.0 the fille log existed but in v.4.4.0 no 


![1p](https://user-images.githubusercontent.com/101944396/185872631-2345cb63-cebf-45b1-93ab-4bac41056653.png)

**Comment by mester90** [comment]
this is the latest.log file

[latest.log](https://github.com/LMH01/MGT2_Mod_Tool/files/9392569/latest.log)

**Comment by LMH01** [comment]
Can you please try to go to the settings and set the MGT2 path manually?

To do that do the following
1. Go to  `Settings -> MGT2 Folder`
2. Select `Manual` from the drop down menu
3. Navigate to the location where MGT2 is installed (not the link file on the desktop, the folder that opens when you click `browse local files` in steam.
4. Save the settings and restart the mod tool.

If that did not work please sent me the latest log file again.

The log file is only placed in the folder once the program is closed again.

**Comment by mester90** [comment]
oh thanks now it works 
i just move the game file from desktop to steamapps/common 
thank youu
and please can you add more countries to the game

**Comment by LMH01** [comment]
No problem :)

Unfortunately I can not add more countries to the game, I already support all countries that are added to the game by default.
