### ISSUE TITLE
Import fails when "Customize import" is checked.

### ISSUE THREAD

**Issue by laureegrd** [LMH01/MGT2_Mod_Tool#126]
This file is giving me an error when I check "Customize Import" on `4.9.0-beta4` (I'm not actually customizing it, just overviewing).

Not clicking that checkbox makes it import correctly, so the bug (if not a mistake in my file, let's hope not this time...) should be somewhere in the customize import code.

[new_content.zip](https://github.com/LMH01/MGT2_Mod_Tool/files/10924185/new_content.zip)

Log:
```
A .zip archive has been found: C:\Users\Luana\Desktop\MGT2 Real Names\new_content.zip
Preparing to unzip folder [C:\Users\Luana\Desktop\MGT2 Real Names\new_content.zip] to [C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0]
Indexing files to unzip: This might take a while
Indexing completed after 0.00 seconds - Beginning to extract files
File unzipped: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\assets
File unzipped: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\assets\eggcode_games.png
File unzipped: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\assets\spectrum_holobyte.png
File unzipped: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\npc_ips.toml
File unzipped: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\publishers.toml
Searching folder: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0
Searching folder: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\assets
Toml file found: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\npc_ips.toml
Toml file found: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\publishers.toml
Search for .toml files complete. Took 0.68 seconds!
Total .toml files found: 2
Analyzing .toml files to determine if they contain mods
Reading toml file: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\npc_ips.toml
Reading toml file: C:\Users\Luana\AppData\Roaming\LMH01\MGT2_Mod_Manager\beta\temp\0\publishers.toml
Found files that contain mods: 2
Single mod files: 0
Bundled mod files: 2
Searching toml files for mods
Found mod: npc_ip - Mad Games Tycoon
Found mod: npc_ip - Mad Tower Tycoon
Found mod that modifies the following content: npc_ip - F-16 Falcon
Found mod: publisher - Spectrum HoloByte
Found mod: publisher - Eggcode Games
Total number of mods found: 5
Already added: 0
Incompatible: 0
Duplicated: 0
Unique: 5
Replace: 0
Modify: 1
Add: 4
Error in thread: ImportAll
The process has been terminated!
Stacktrace:
java.lang.NullPointerException
	at java.lang.String.contains(Unknown Source)
	at com.github.lmh01.mgt2mt.util.manager.SharingManager.getCustomizedImportMap(SharingManager.java:353)
	at com.github.lmh01.mgt2mt.util.manager.SharingManager.importAll(SharingManager.java:173)
	at com.github.lmh01.mgt2mt.util.manager.SharingManager.importAll(SharingManager.java:48)
	at com.github.lmh01.mgt2mt.windows.WindowMain.lambda$null$6(WindowMain.java:107)
	at com.github.lmh01.mgt2mt.util.handler.ThreadHandler.lambda$startModThread$3(ThreadHandler.java:144)
	at java.lang.Thread.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by LMH01** [comment]
Fixed in v4.9.0-beta5
